### PR TITLE
Removing dependence on OpenCL SDK

### PR DESCRIPTION
**Pull request by yixuan**
This PR is a follow-up of #31. It removes the dependence on OpenCL SDKs during the installation process, so that users only need runtime drivers to use this package. It is also expected that after this change, CRAN can directly build binary packages for Windows and Mac.

## How it works

To build `gpuR` one needs the OpenCL headers and the so-called ICD loader in the form of a `OpenCL.dll` or `libOpenCL.so` file. This ICD loader is just a simple program to select the real implementation of OpenCL, and it is open source at https://github.com/KhronosGroup/OpenCL-ICD-Loader. Hence we can include the OpenCL headers and the source code of ICD loader in the package to avoid using compiled libraries from OpenCL SDKs.

## Changes to configuration scripts

The major changes to the configuration scripts in the current `develop` branch is documented below.

- Windows
    - `configure.win` is removed since we will build ICD loader from source.
    - `Makevars.win` is updated to build the ICD loader
- Mac
    - All modern Mac OSs have OpenCL headers and libraries preinstalled, and GCC can find their locations by adding the `-framework OpenCL` flag. We won't fail the configure script even if `OPENCL_INC` is not set
- Linux
    - First test the existence of environment variables such as `OPENCL_INC` and `OPENCL_LIB`. If not found, build the ICD loader using the code included in package. So we won't fail the configure script either

I have tested this PR on Windows and Linux on my own machine. There may still be some issues that require another several rounds to fix, but I think this is a starting point.

### CODE REVIEW

**Comment by cdeterman** [comment]
@yixuan There appears to be an error in the Makevars file mentioned in the Travis CI linux build:

> Makevars:6: *** missing separator.

**Comment by yixuan** [comment]
Yeah, I noticed that. I guess this is due to different behavior of the `make` program. I'll do some debugging on that. Thanks.

**Comment by yixuan** [comment]
It looks to work now. :smile:

**Comment by cdeterman** [comment]
Great, I was just looking over the code (primarily the configure file) and I noticed that in the event that the OpenCL is compiled from source (line 112) it appears that the OpenCL headers used are still from the system or from `OPENCL_INC`.  Was that the intent or was it to use the headers in the src/CL directory you added in that case?

**Comment by cdeterman** [comment]
@yixuan If it is the latter (use `src/CL` headers) then we will probably want to restructure the package to the headers of in the `inst` directory.  This is much more standard in R packages and then the headers can be used by other packages linking to this package as well as the internals which use the headers.

**Comment by yixuan** [comment]
I see. When we decide to compile from the source, we first look whether the system has OpenCL headers installed (https://github.com/yixuan/gpuR/blob/battery-included/configure#L127-L133). If still not, we finally use the included headers (https://github.com/yixuan/gpuR/blob/battery-included/configure#L134-L135).

**Comment by cdeterman** [comment]
Ah, I see now, didn't look close enough.  Regarding the structure of the package I think I will do some tests of my own after merging this branch.  I think this is certainly a valuable addition.  Thanks @yixuan.

**Comment by yixuan** [comment]
Sure. Given that this is comparatively a big change, we may need several rounds of modification to ensure that it really works.

**Pull request merged**
